'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    // Define the parent menus
    const parentMenus = [
      {
        id: 1,
        type: "dropdown",
        title: "Dashboard",
        iconClass: "ph-duotone ph-house-line",
        name: "dashboard",
        badgeCount: 4,
        collapseId: "dashboard",
        path: '/dashboard',
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        type: "dropdown",
        title: "Pelayanan",
        iconClass: "ph-duotone ph-user-circle-plus",
        name: "pendaftaran",
        badgeCount: 5,
        collapseId: "pendaftaran",
        path: '/pendaftaran',
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Pelayanan",
        path: '/pendaftaran/pelayanan',
        iconClass: "ph-duotone ph-folder-simple-plus",
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        type: "dropdown",
        iconClass: "ph-duotone ph-tooth",
        name: "odontogram",
        badgeCount: 5,
        collapseId: "odontogram",
        path: '/odontogram',
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        type: "dropdown",
        iconClass: "ph-duotone ph-bookmarks-simple",
        name: "laboratorium",
        badgeCount: 5,
        collapseId: "laboratorium",
        path: '/laboratorium',
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        type: "dropdown",
        title: "Laporan",
        iconClass: "ph-duotone ph-chart-bar",
        name: "kunjungan",
        collapseId: "laporan",
        path: '/laporan',
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        type: "dropdown",
        iconClass: "ph-duotone ph-chart-line-down",
        name: "keuangan",
        collapseId: "keuangan",
        path: '/keuangan',
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        type: "dropdown",
        title: "Master",
        iconClass: "ph-duotone ph-toolbox",
        name: "Obat",
        collapseId: "ui-kits",
        path: '/ui-kits',
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Poli",
        path: '/master/poli',
        iconClass: "ph-duotone ph-house",
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Dokter",
        path: '/master/dokter',
        iconClass: "ph-duotone ph-user-minus",
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "Penjamin",
        path: '/master/penjamin',
        iconClass: "ph-duotone ph-credit-card",
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        name: "Tarif",
        path: '/master/tarif',
        iconClass: "ph-duotone ph-currency-circle-dollar",
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        name: "Karyawan",
        path: '/master/karyawan',
        iconClass: "ph-duotone ph-users-three",
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        name: "Supplier",
        path: '/master/supplier',
        iconClass: "ph-duotone ph-squares-four",
        parent_id: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    // Define the child menus
    const childMenus = [
      {
        name: "Ecommerce",
        path: "/dashboard/ecommerce",
        parent_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Project",
        path: "/dashboard/project",
        parent_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rawat Jalan",
        path: "/pendaftaran/ecommerce",
        parent_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rawat Inap",
        path: "/pendaftaran/project",
        parent_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pendaftaran",
        path: "/pendaftaran/ecommerce",
        parent_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pendaftaran",
        path: "/pendaftaran/ecommerce",
        parent_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pasien Rawat Jalan",
        path: "/ui-kit/cheatsheet",
        parent_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pasien Rawat Inap",
        path: "/ui-kit/cheatsheet",
        parent_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Laboratorium",
        path: "/ui-kit/cheatsheet",
        parent_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pasien Rawat Jalan",
        path: "/ui-kit/cheatsheet",
        parent_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pasien Rawat Inap",
        path: "/ui-kit/cheatsheet",
        parent_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Laboratorium",
        path: "/ui-kit/cheatsheet",
        parent_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Cheatsheet",
        path: "/ui-kit/cheatsheet",
        parent_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    // Insert parent and child menus
    await queryInterface.bulkInsert('menus', [...parentMenus, ...childMenus]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('menus', null, {});
  },
};
